HBO España
arvvoid/plugin.video.hbogoeu pull request #13
Opened 2019-04-07 18:09 UTC by Sakerdot

https://github.com/arvvoid/plugin.video.hbogoeu/issues/6

Starting point for the development of HBO España.

ATM only https://es.hboespana.com/ login endpoint is supported, there isn't any info on episodes/seasons/tv shows but at least they can be played.

Code right now is messy and probably bug ridden, but if someone wanted to use HBO España on Kodi (specially after 15th of April...) here you go.

2019-04-07 18:11 UTC, Sakerdot commented
It probably shouldn't be merged right now, I just wanted to have something to play HBO before the last GoT season is released.

2019-04-08 07:50 UTC, arvvoid commented
Hello, good job :) I like the direction where this is going. Can't test the Spain handler because I don't have a Spain account but tested the add-on with your changes and it does not break any existing functionality, so it can be safely merged at any time.

For now, I will wait with merging until this is more mature and tested.

I made a zip for easy installation of your version so far, for easy testing: 
[plugin.video.hbogoeu-spain.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/3053190/plugin.video.hbogoeu-spain.zip)

2019-04-11 06:37 UTC, arvvoid commented
@Sakerdot got confirmation that this work for HBO Nordic as well #7 with just modifying the URLs.

for spain is api-hbo**e**, for nordic api-hbo**n**   and self.API_HOST_GATEWAY = 'https://en.hbonordic.com/'

2019-04-12 06:34 UTC, arvvoid requested changes
Some minor changes that will make the session persistent, not make it generate a new device uuid on each request, add support for Nordic

2019-04-12 06:34 UTC, arvvoid commented on hbogolib/handlersp.py
> +        self.API_DEVICE_ID = self.generate_device_id()
This way the device id will be generated on every add-on call my suggestion is to save device id to settings:

```
self.API_DEVICE_ID = self.addon.getSetting('individualization')

if (self.API_DEVICE_ID == ""):
    self.log("NO REGISTRED DEVICE - generating")
    self.API_DEVICE_ID = self.generate_device_id()
    self.addon.setSetting('individualization', str(self.API_DEVICE_ID))

```

2019-04-12 06:34 UTC, arvvoid commented on hbogolib/handlersp.py
> +            self.init_api()
Save sucessful login for reuse on next add-on calls:

```
 login_hash = hashlib.sha224(self.API_DEVICE_ID + username + password).hexdigest()
 self.log("LOGIN HASH: " + login_hash)
 saved_session = {

                "hash": login_hash,
                "API_DEVICE_TOKEN": self.API_DEVICE_TOKEN,
                "API_IDENTITY_GUID": self.API_IDENTITY_GUID,
                "API_ACCOUNT_GUID": self.API_ACCOUNT_GUID,
                "time": time.time()

}
self.save_obj(saved_session, self.addon_id + "_es_session")
```

2019-04-12 06:34 UTC, arvvoid commented on hbogolib/handlersp.py
> +
Before login check if there is a saved valid successful login:

```
login_hash = hashlib.sha224(self.API_DEVICE_ID + username + password).hexdigest()
self.log("LOGIN HASH: " + login_hash)

loaded_session = self.load_obj(self.addon_id + "_es_session")

if loaded_session != None:
    self.log("SAVED SESSION LOADED")
    if loaded_session["hash"] == login_hash:
      self.log("HASH IS VALID")
      if time.time() < (loaded_session["time"] + (self.SESSION_VALIDITY * 60 * 60)):
          self.log("NOT EXPIRED RESTORING...")
          self.API_DEVICE_TOKEN = loaded_session["API_DEVICE_TOKEN"]
          self.API_IDENTITY_GUID = loaded_session["API_IDENTITY_GUID"]
          self.API_ACCOUNT_GUID = loaded_session["API_ACCOUNT_GUID"]
          self.init_api()
          loaded_session['time'] = time.time()
          self.save_obj(loaded_session, self.addon_id + "_es_session")
          return True
```

2019-04-12 06:34 UTC, arvvoid commented on hbogolib/constants.py
> +        ['Spain', 'es', 'es', '', '', '', HANDLER_SPAIN],
To add support for HBO Nordic as well here we need to modify and add:

```
        ['Spain', 'es', 'es', 'ESP', 'ESP', 'https://es.hboespana.com', HANDLER_SPAIN],
        ['Norway', 'no', 'no', 'NOR', 'NOR', 'https://no.hbonordic.com/', HANDLER_NORDIC],
        ['Denmark', 'dk', 'dk', 'DNK', 'DNK', 'https://dk.hbonordic.com/', HANDLER_NORDIC],
        ['Sweden', 'se', 'se', 'SWE', 'SWE', 'https://se.hbonordic.com/', HANDLER_NORDIC],
        ['Finland', 'fi', 'fi', 'FIN', 'FIN', 'https://fi.hbonordic.com/', HANDLER_NORDIC],
```

2019-04-12 06:34 UTC, arvvoid commented on hbogolib/handlersp.py
> +    def __init__(self, handle, base_url):
change to: (self, handle, base_url, country):

2019-04-12 06:34 UTC, arvvoid commented on hbogolib/base.py
> +            self.handler = HbogoHandler_sp(self.handle, self.base_url)
change to: self.handler = HbogoHandler_sp(self.handle, self.base_url, HbogoConstants.countries[country_index])

2019-04-12 06:34 UTC, arvvoid commented on hbogolib/handlersp.py
> +        license_url = 'https://api-hboe.hbo.clearleap.com/cloffice/drm/wv/' + media_guid + '|' + license_headers + '|R{SSM}|'
change to:

`license_url = 'https://'+ self.API_HOST + '/cloffice/drm/wv/' + media_guid + '|' + license_headers + '|R{SSM}|'`

2019-04-12 06:34 UTC, arvvoid commented on hbogolib/handlersp.py
> +        self.API_HOST = 'api-hboe.hbo.clearleap.com'
Change to support HBO Nordic with this handler:

```
        if country[1] == 'es':
            self.API_HOST = 'api-hboe.hbo.clearleap.com'
        else:
            self.API_HOST = 'api-hbon.hbo.clearleap.com'
        
        self.API_HOST_GATEWAY = country[5]
        self.API_HOST_GATEWAY_REFERER = self.API_HOST_GATEWAY + '/sign-in'

        self.API_URL_BROWSE = 'https://'+  self.API_HOST +'/cloffice/client/web/browse/'
        self.API_URL_AUTH_WEBBASIC = 'https://'+  self.API_HOST + '/cloffice/client/device/login'
```

2019-04-12 06:34 UTC, arvvoid commented on hbogolib/handlersp.py
> +    def generate_device_id(self):
This can be changed to:

import uuid
return uuid.uuid4()

2019-04-18 07:35 UTC, arvvoid approved these changes

2019-04-18 07:55 UTC, arvvoid commented
New test version for Spain and Nordic please test and report back, please perform all actions and provide debug logs even in all seems to work fine.
[plugin.video.hbogoeu.test.spno.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/3093273/plugin.video.hbogoeu.test.spno.zip)

2019-04-18 10:49 UTC, PolliSoft commented
Thanks for the test version. Unfortunately it crashes on start, after login. See https://pastebin.com/izZUXkcZ for debug log.
File "C:\Users\Olof\AppData\Roaming\Kodi\addons\plugin.video.hbogoeu\hbogolib\handlersp.py", line 141, in login
                                                "time": time.time()
                                            NameError: global name 'time' is not defined

2019-04-18 11:30 UTC, arvvoid commented
@PolliSoft tnx for reporting

Fixed version: 
[plugin.video.hbogoeu.test.spno.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/3094164/plugin.video.hbogoeu.test.spno.zip)

2019-04-18 12:11 UTC, PolliSoft commented
Installed new version, and it works like a charm! No problem with sessions, all videos played as they should (tested around 20 of them).
Still no subtitles.

2019-04-18 17:51 UTC, macardi commented
Hi, done some testing with the new version. It seems to work fine, no errors.

Logg: https://paste.ubuntu.com/p/3nnVnMdy65/

2019-04-18 20:08 UTC, jhdgghost commented
Confirmed working hbo spain. But the subtitles are not working

2019-04-18 21:57 UTC, arvvoid commented
Tnx for reporting.
Like i suspected subtitles are missing from the mpd manifest will habe to be handled diferently.
Will get solved just need some time to work on it.
I will need a full debug log from Spain as well to work on the subtitles.

2019-04-18 22:07 UTC, Sakerdot commented
Hey, great progress! I haven't had any time, hopefully I'll be able to help more soon.

2019-04-18 22:46 UTC, jhdgghost commented
[01_KODI.log](https://github.com/arvvoid/plugin.video.hbogoeu/files/3096396/01_KODI.log)
Here one debug log from hbo spain. I hope i did correctly if not tell me and i try to do again. I check and there is audio options but not subs.

2019-04-19 06:38 UTC, arvvoid commented
@jhdgghost It's fine, for the future you can follow the steps described here: https://kodi.wiki/view/Log_file/Easy

2019-04-19 13:40 UTC, sanangel commented
@arvvoid ha, If there is any way to help so that the menus and titles of the films and series are in Spanish, let me know if I can help

2019-04-19 13:56 UTC, macardi commented
Will movie, TV show and episode info and artwork, be supported in the future.

2019-04-19 22:00 UTC, arvvoid commented
@sanangel  i think i figured out the languages, will implement it when i have a little spare time and then some testing will be needed for both Spain and Nordic. Also will need somebody to make language files.
Please take a look at ISSUE #3 for instructions and to submit  a translation.

@macardi yes soon i have the info necessary in the debug logs, but will take some trial and error probably.

2019-04-19 22:09 UTC, arvvoid commented
It looks like to set the content language `?language=lang_code` have to be added to the api calls.

Language codes for Spain:

```
es_hboespana Spanish
en_hboespana English
```

Language codes for Nordic:

```
en_hbon English
da_hbon Dansk
no_hbon Norsk
fi_hbon Suomi
sv_hbon Svenska
```

2019-04-20 13:46 UTC, arvvoid commented
Test release with language support and basic media info: 
[plugin.video.hbogoeu.test.spno.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/3100172/plugin.video.hbogoeu.test.spno.zip)

Please keep in mind I have no clue if this will work at all since I can't test it, try, and report back with full debug logs (follow these steps for the log https://kodi.wiki/view/Log_file/Easy). If it doesn't work post a log and revert to the previous version.

There is no language files yet so it will default to English no matter what your Kodi is set to.
To make read your local language from hbogo, go to the add-on configuration and turn on **Force default operator language**. This will have an effect only on the content retrieved from Hbo go but will not translate the add-on interface (messages, labels) for that I will need someone to do the translations as instructed in #3 

@PolliSoft @macardi @jhdgghost @sanangel

2019-04-20 13:58 UTC, jhdgghost commented
I just tested and not working.

ERROR: GetDirectory - Error getting plugin://plugin.video.hbogoeu/
2019-04-20 15:48:45.127 T:1937490720   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.hbogoeu/) failed

Revert to the previous one and working again.

2019-04-20 14:02 UTC, arvvoid commented
How did you install the add-on did you use the install from zip function in kodi?
Please post full debug logs

2019-04-20 14:14 UTC, jhdgghost commented
[01_KODI.log](https://github.com/arvvoid/plugin.video.hbogoeu/files/3100215/01_KODI.log)
Here the debug log. Yes i install from the zip function in kodi.

2019-04-20 14:37 UTC, macardi commented
Im also get a login error. I did what I usually do, just downloded the zip-file and extracted it and pase it in the Kodi addon library after deleating the old addon folder.

Log: https://pastebin.com/mDp6GZ1R

I will give the translation for Swedish a go later this week.

2019-04-20 21:52 UTC, arvvoid commented
Try this, it has basic media info, Spanish language file (contribution of @jhdgghost), support for local languages: 
[plugin.video.hbogoeu-esnotest.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/3100620/plugin.video.hbogoeu-esnotest.zip)

there is still a lot of room for improvement.

If your Kodi language is English or there is no language file in the add-on for your local language yet you have to enable Force default operator language in the add-on settings to make it retrieve content in your local language.

The recommended install method is using the install addon from zip function in Kodi. (in case it was previously installed in another way, removing the add-on and properly installing is recommended)

@PolliSoft @macardi @jhdgghost @sanangel @Sakerdot 

Work in progressSubtitles.

Things to add later on that i can't work on for lack of access:

- My List
- Context menus
- Add to my list
- Remove from my list
- Voting
- Search

2019-04-20 22:16 UTC, sanangel commented
@arvvoid ha If you need access, i can vive my id for prívate message

2019-04-20 22:39 UTC, arvvoid commented
@sanangel tnx but no need, your account could get blocked for different geolocation access. I get the info I need to help from the debug logs. 

Does the last test version work for you, can you provide a full debug log?

2019-04-20 23:07 UTC, jhdgghost commented
Just tested and is working fine. Nothing broken 👍

2019-04-21 11:48 UTC, sanangel commented
> @sanangel tnx but no need, your account could get blocked for different geolocation access. I get the info I need to help from the debug logs.
> 
> Does the last test version work for you, can you provide a full debug log?

Yes, the latest version translated into Spanish and with information on the chapters and films works for me.
Although I miss some series of cartoons like Mundo Pocoyo.
If you inform me how to make a record, I will be delighted.
Thanks for all your work.

2019-04-22 13:19 UTC, macardi commented
Hi, at last I got some time away from the family to test the new version. It works very well. Info and art is there for the most part, missing info is year, genre, runtime as far as I can see. 

Log: https://paste.ubuntu.com/p/kSm8V3P5H7/

2019-04-22 18:36 UTC, jumakki commented
Hi, thanks for great plugin!
I bumped into one issue which prevented login from me.
I got exception ending with:
```
File "/storage/.kodi/addons/plugin.video.hbogoeu/hbogolib/handler.py", line 252, in get_device_id_v1
                                                return hashlib.sha256(codecs.encode(str(mac), 'rot_13') + self.addon_id + '.credentials.v1.' + codecs.encode(str(space), 'rot_13')).digest()
File "/usr/lib/python2.7/encodings/rot_13.py", line 17, in encode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
```
My UI language is Finnish and 'space' contained a non-ascii character 'ä' in UTF-8: "227 MB Yhteensä"

Everything worked with Nordic after I hard-coded 'space' content to something else.

2019-04-23 18:47 UTC, arvvoid commented
@jumakki Hello, tnx for reporting. A fix will be availible soon. If you have some spare time you can check #3 and submit a Finnish translation.

2019-04-23 23:18 UTC, arvvoid commented
@jumakki Try please if this fix the login problem for you. It will ask you for credentials again, will not be able to decode your current credentials since your custom change. 
After you input credentials again it should work.

[plugin.video.hbogoeu-esnotest.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/3109918/plugin.video.hbogoeu-esnotest.zip)

2019-04-24 18:15 UTC, alfem commented
Hi!  Another spanish user here.

I have tested the last version (https://github.com/arvvoid/plugin.video.hbogoeu/pull/13#issuecomment-485180020) but login shows an error notification. 

Curiosly I can access the films catalog, but no content get played.  

I can see this python error in my log:

https://pastebin.com/q4LjUjK8

Also tested the last .zip but it fails during installation.

2019-04-24 18:51 UTC, jumakki commented
> @jumakki Try please if this fix the login problem for you.

Thanks! That fixed the problem.

2019-04-24 20:23 UTC, arvvoid commented
@alfem please post a full debug log. Browsing partialy work without login.

2019-04-25 18:27 UTC, alfem commented
Here you have the full log, after plugin deletion and fresh reinstall.

 https://paste.kodi.tv/isamatacuz.kodi

I hope it helps

2019-04-26 05:06 UTC, arvvoid commented
@alfem do you by any chanse have a character outside the ascii range in you username or password? http://www.asciitable.com

2019-04-26 11:22 UTC, alfem commented
Mmm, I am afraid not. Username is a gmail account with a dot in the middle (and the @ symbolf, obviously). And my probably unsafe password only contains simple ascii characters.

2019-04-27 11:58 UTC, arvvoid commented
@alfem ok, will make a tentative fix in next version but not really sure whats the cause right now, since others dont report same problem.

Next version will include a workaround for missing subtitles as well. Subtitles seams are missing from manifest thats why dont get processed by inputstream. So probably hbo spain nordic handles them in some non standard way.  
So the addon will download the subtitle in local language separatly from hbo go convert it from ttml format to srt and set it in videoplayer, will take me some more days to finish that.

2019-04-27 12:06 UTC, Tr1aX commented
I just updated to (through install from zip function in kodi) and tested the last version. On first try I got a login error notification, but worked well the second time I tried. 
Playback is perfect like before, and menus are in Spanish now with basic media info (artwork and episode synopsis) but maybe menu navigation is a bit slower now. Thanks for your work!

2019-04-27 22:40 UTC, arvvoid commented
Test version with Swedish and Finnish language file and subtitles workaround (enable in add-on settings). This is not tested at all so it might not work right away please report any problems.

@alfem This contains a tentative fix for your problem as well. Remove the add-on and add-on data completely and install this version and try, please report the outcome.

[plugin.video.hbogoeu-esnotest.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/3124417/plugin.video.hbogoeu-esnotest.zip)

2019-04-28 06:16 UTC, jhdgghost commented
I install from zip file option in kodi. The addon is working but not see any option in the settings for the subtitles.

2019-04-28 08:41 UTC, arvvoid commented
Fix for the option, the option will be enabled by default: 
[plugin.video.hbogoeu-esnotest.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/3124748/plugin.video.hbogoeu-esnotest.zip)

2019-04-28 08:48 UTC, jhdgghost commented
Just tested, the option now appears.But i test a couple of episodes and the subtitles not appear. Tell me if you need debug log

2019-04-28 08:59 UTC, jhdgghost commented
An update. I tested game of thrones season 8 episode 2 and no subs but in s08E01 there is spanish subtitles. Tested also series The warrior none of the four episodes available have subtitles.

2019-04-28 09:12 UTC, jhdgghost commented
[01_KODI.log](https://github.com/arvvoid/plugin.video.hbogoeu/files/3124783/01_KODI.log)
Here a debug log with working sub episodes and not working.

2019-04-28 20:23 UTC, arvvoid commented
Try this version and please provide debug logs, also after playing something with subtitles in _.Kodi/userdata/addon_data/plugin.video.hbogoeu_  a folder named subs will get created containing the downloaded and converted subtitles please zip and send the content of the subs folder as well if possible.

[plugin.video.hbogoeu-esnotest.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/3125462/plugin.video.hbogoeu-esnotest.zip)

2019-04-28 20:51 UTC, PolliSoft commented
Tested, and noticed the following things:
* No correct images for any media (Series/movies/episode thumbnails), only the default HBO image shown instead.
* Error when trying to play any media, debug log here: https://pastebin.com/AnXwT82j
2019-04-28 22:44:19.766 T:10716   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: bad operand type for unary +: 'str'
                                            Traceback (most recent call last):
                                              File "C:\Users\Olof\AppData\Roaming\Kodi\addons\plugin.video.hbogoeu\main.py", line 24, in <module>
                                                addon_main.router(REQUEST_PARAMS)
                                              File "C:\Users\Olof\AppData\Roaming\Kodi\addons\plugin.video.hbogoeu\hbogolib\base.py", line 143, in router
                                                self.handler.play(url, content_id)
                                              File "C:\Users\Olof\AppData\Roaming\Kodi\addons\plugin.video.hbogoeu\hbogolib\handlersp.py", line 314, in play
                                                self.log("Manifest: " + + ET.tostring(mpd, encoding='utf8'))
                                            TypeError: bad operand type for unary +: 'str'
                                            -->End of Python script error report<--

2019-04-28 21:02 UTC, arvvoid commented
@PolliSoft tnx, i done this in a hurry made some typos will fix it tomorrow.

2019-04-29 10:31 UTC, arvvoid commented
Try this version: 
[plugin.video.hbogoeu-esnotest.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/3126985/plugin.video.hbogoeu-esnotest.zip)

2019-04-29 14:00 UTC, arvvoid commented
Try this: 
[plugin.video.hbogoeu-esnotest.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/3127653/plugin.video.hbogoeu-esnotest.zip)

2019-04-29 16:43 UTC, PolliSoft commented
Tested it, debug log here: https://pastebin.com/3iFGFrAW
No subtitles shown, but one Norwegian subtitle file (no_hbon.xml) downloaded to c:\Users\olof\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.hbogoeu\subs\1f10ced-01092cdc642\. In the same folder, there is also a 0B no_hbon.srt, nothing else. 
Is there anything else I can upload to help?

2019-04-29 17:08 UTC, jumakki commented
Hard coded '/' are not the problem.
I added some debug logging and it fails in Ttml2srt::extract_dialogue() when it bumps into non-ascii character.
I tested with GoT episode 3 and nordic languages fail quite soon,
I skipped others than English but it fails too when it gets this line:
`<p xml:id="13" xml:space="preserve" begin="00:09:03:07" end="00:09:06:16" tts:backgroundColor="black" tts:fontSize="36px" tts:origin="0px 437px"><span tts:fontStyle="italic">-Valar morghulis.</span><br /><span tts:fontStyle="italic">-Valar dohaeris.</span></p>`
It is first text line with that span italic.

2019-04-29 17:55 UTC, jumakki commented
English with that span failed because there was "self." missing  from this line in ttml2srt.py around line 30 when calling recursively extract_dialogue():
`            if node.hasChildNodes():
                dialogue = dialogue + self.extract_dialogue(node.childNodes)
`

2019-04-29 18:54 UTC, PolliSoft commented
Thanks a lot for this, @jumakki. I did the change and all subs are now working!

2019-04-29 21:01 UTC, arvvoid commented
@jumakki @PolliSoft tnx for your contributions and testing. Fixed it.

This version should do the trick let me know the outcome.

[plugin.video.hbogoeu-esnotest.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/3129176/plugin.video.hbogoeu-esnotest.zip)

2019-04-30 10:12 UTC, jhdgghost commented
Tested. And the everything is working perfectly. Several episodes tested and english and spanish subs are available. Thanks fir the fix

2019-04-30 17:38 UTC, jumakki commented
@arvvoid Thanks, works perfectly!

2019-04-30 18:39 UTC, macardi commented
Just tested the new version, works very well also at my end. Thanks a lot!

2019-05-02 06:22 UTC, arvvoid commented
Now remains to see how to get my list, and the api call to add to my list and remove from my list, and the api call to vote.

After that, this is ready to be merged, and included in the standard releases.

2019-05-02 13:07 UTC, sanangel commented
Thanks @arvvoid ha for all your work 
The last version work perfect.

2019-05-02 18:35 UTC, jhdgghost commented
A little question the version of this branch is lower than of the main branch. As I have installed the repository an the update notification is always there and i have to enter in the addon section to confirm if there is another addon update and can not select update all if i do not want hbogoeu addon get updated to last main branch. 

Can I manually change the version so it is the same than the main branch so the update notification for this addon disappears? Disabling the repository not work

I know is it an stupid thing but I am curious to know if i can do it myself and also happens to me previously with Netflix addon for example.

2019-05-02 18:44 UTC, arvvoid commented
@jhdgghost you can simply disable automatic updates for this add-on untill it get merged. If you want to manualy change the version to the same as the main branch nothing bad will happen.

2019-05-03 19:39 UTC, alfem commented
> @alfem This contains a tentative fix for your problem as well. Remove the add-on and add-on data completely and install this version and try, please report the outcome.

It works! 

Well, sound is in English (but menus and titles are in Spanish). I do not know if this is the expected behaviour.

We are reaaally close! Thanks for your amazing work!

2019-05-05 13:29 UTC, arvvoid commented
@alfem Glad it works! 
What audio tracks are availible depends on the content and what hbo provide an specify in the manifest. You can change beetween availible audio stream in the audio menu during playbeck, thats beyond the add-on control get handled by inputstream.adaptive.
To set default audio and subtite language go to Kodi Settings -> appearance -> international you should be able to select your default audio and subtitle language (will get autoselected if availible in the stream).

2019-05-06 09:08 UTC, jhdgghost commented
[en_hboespana.en-US.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3147194/en_hboespana.en-US.txt)

A little issue i find in last episode of game of thrones 8x04. After 1 hour the subs dissapear. I upload the sub. It is clear that the problem is that the time is wrong because the minutes are not reset to zero after one hour. Happens the same in english and spanish subs. Not sure if it is addon error or is a problem in the subs downloaded. Also check game of thrones 8x03 and happens the same. Seems a problem with more than one hour episodes.

2019-05-06 10:53 UTC, arvvoid commented
@jhdgghost its probably a bug in the ttml to srt converter will look into it. Please post the original subs in ttml format as well so i can debug the converter

2019-05-06 15:17 UTC, alfem commented
> @alfem Glad it works!
> What audio tracks are availible depends on the content and what hbo provide and specify in the manifest. You can change beetween availible audio streams in the audio menu during playbeck, thats beyond the add-on control, get handled by inputstream.adaptive.

That made the trick! 
I had got kodi with language setting as 'default' and English is the default for almost everything. I did not notice this because my kodi interface is in Spanish.

I hope you could merge this branch soon. Thanks for your help!

2019-05-06 19:35 UTC, jumakki commented
Counting minutes has a bug in ms_to_subrip() in ttlm2srt.py
Just int(ms / 60000) isn't enough. Would need to substract hours * 60 from it.
It worked when changed to this:
```
    def ms_to_subrip(self, ms):
        return '{:02d}:{:02d}:{:02d},{:03d}'.format(
            int(ms / (3600 * 1000)),  # hh
            int(ms / 60000 - (ms / (3600 * 1000) * 60)),  # mm
            int((ms % 60000) / 1000),  # ss
            int((ms % 60000) % 1000))  # ms
```

2019-05-06 20:10 UTC, jhdgghost commented
The subs in xml. 
[en_hboespana.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3149683/en_hboespana.txt)

2019-05-07 06:43 UTC, arvvoid commented
Fixed subtitles version: 
[plugin.video.hbogoeu-esnotest.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/3151094/plugin.video.hbogoeu-esnotest.zip)

Tnx @jumakki and tnx @jhdgghost for reporting.

I'm planning of merging this soon will leave it for couple more days, i think this is ready to be used and tested by more people now.
Then the missing features SEARCH, MY LIST, ADD/ROMOVE FROM MY LIST AND VOTING can be added with new pull request/s.
After merging i will start working on the kodi library integration feature.
What you all think about that? @Sakerdot @jumakki

2019-05-07 06:50 UTC, sanangel commented
It works perfectly, although some options are missing, it is more than suitable for daily use.

2019-05-07 14:56 UTC, Sakerdot commented
I've tried it a little bit and it seems fine, I'll have time again by the end of June, hopefully I can help then.

2019-05-07 14:58 UTC, jumakki commented
I agree. It's ready for merging

2019-05-08 06:19 UTC, merged

2019-10-28 11:45 UTC, arvvoid commented
@all-contributors please add @Sakerdot  for code, ideas

2019-10-28 11:49 UTC, arvvoid commented
@all-contributors please add @PolliSoft for bug, test

2019-10-28 11:52 UTC, arvvoid commented
@all-contributors please add @PolliSoft for bug, test

2019-10-28 12:00 UTC, arvvoid commented
@all-contributors please add @macardi for translation, test

2019-10-28 12:01 UTC, arvvoid commented
@all-contributors please add @jhdgghost for translation, test

2019-10-28 12:02 UTC, arvvoid commented
@all-contributors please add @jumakki  for translation, test, bug, ideas

2019-10-28 12:04 UTC, arvvoid commented
@all-contributors please add @sanangel  for testing

2019-10-28 12:05 UTC, arvvoid commented
@all-contributors please add @alfem for testing