Updating Swedish language
arvvoid/plugin.video.hbogoeu pull request #161
Opened 2020-05-10 22:46 UTC by Sopor

## Please check that your pull request pass this checks:

-  [ ] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
-  [ ] My code is both Python 2 and 3 compatible
-  [ ] My code follows the code style of this project (PEP8, long lines allowed if make sense)
-  [ ] I made sure there wasn't another Pull Request opened for the same update/change
-  [ ] I have successfully tested my changes locally

## Types of changes

-  [ ] Bug fix (non-breaking change which fixes an issue)
-  [ ] New feature (non-breaking change which adds functionality)
-  [ ] Breaking change (fix or feature that would cause existing functionality to change)
-  [ ] Adding a new region/hbo go version

## Description:

2020-05-11 06:22 UTC, arvvoid requested changes
Hello, thank you for your submission. 
Now that the translation is complete and checked just remove the #fuzzy flag from strings where present and I can merge this and include in a release.

2020-05-11 06:22 UTC, arvvoid commented on resources/language/resource.language.sv_se/strings.po
>  #, fuzzy
Please remove the fuzzy flag

2020-05-12 07:12 UTC, arvvoid requested changes
Hello @Sopor, there was an additional fuzzy flag left, I removed it. Now all is ok, I just noticed one string left untranslated #30005

2020-05-12 07:12 UTC, arvvoid commented on resources/language/resource.language.sv_se/strings.po
>  msgctxt "#30005"
This string is untranslated

2020-05-12 10:36 UTC, Sopor commented on resources/language/resource.language.sv_se/strings.po
>  msgctxt "#30005"
Sorry, but it is fixed now :)

2020-05-12 11:47 UTC, arvvoid approved these changes

2020-05-12 11:51 UTC, arvvoid commented
Now is ready for merging I just edited the last translator and revision date in the file

2020-05-12 11:54 UTC, merged

2020-05-12 11:56 UTC, arvvoid commented
@all-contributors please add @Sopor for translation